- project:
    templates:
      - openstack-python3-zed-jobs
      - openstack-cover-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    vars:
      rtd_webhook_id: '224878'
